import "./globals.css";
import { Hanken_Grotesk } from "next/font/google";
const font = Hanken_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Aniruddh",
  description: "Generated by icantcodefyi (Aniruddh)",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-[#111010] flex justify-center`}>
        {children}
      </body>
    </html>
  );
}
